# See: https://pre-commit.com/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
#    -   id: requirements-txt-fixer
    -   id: mixed-line-ending
    -   id: check-added-large-files
